# Welcome to Jekyll!

# Website settings
title: Ferdinand Mom
description: #Jack's blog,use Jekyll and github pages.
keywords: #Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl: # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://ferdinandmom.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Ferdinand Mom  # Be used at blog posts' author.
  first_name: Ferdinand  # Be used at index page about me section.
  last_name: Mom  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpeg  # upload your avatar at directory and edit it.
  github_username: 3outeille  # Leave blank if you don't have now
  linkedin_id: ferdinand-mom-b74770173/ # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: ferdinand.mom@epita.fr  # Leave blank if you don't have now
  cv: https://drive.google.com/file/d/1mrRpIc048j-z47i00eBf2ZayPFQF6ZZc/view?usp=sharing # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fas fa-bullseye
    - name: fa fa-lightbulb-o
  skill_icon2:
    - name: fas fa-language
    - name: fas fa-tree
  desc: French Computer Science & Engineering student at  <a href="https://www.epita.fr/" target="_blank">EPITA</a> with strong interest in Problem Solving, Machine Learning/Deep Learning, Languages and Natural Environment. My <a href="https://drive.google.com/file/d/1mrRpIc048j-z47i00eBf2ZayPFQF6ZZc/view?usp=sharing" target="_blank">resume</a>.

# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: jalpc

# analytics
## google analytics
#ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#  id: UA-93473370-3

## google optimize
#go:
  # id:

## growingIO
#gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

